# Generated by Django 2.1.7 on 2019-03-23 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id_str', models.CharField(default='', max_length=100)),
                ('text', models.TextField(default='', max_length=280)),
            ],
        ),
    ]
