# Generated by Django 2.1.7 on 2019-03-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.CharField(default='created_at', max_length=100)),
                ('tweet_id_str', models.CharField(default='tweet_id_str', max_length=100)),
                ('text', models.TextField(default='TextField', max_length=280)),
                ('country', models.CharField(default='usa', max_length=200)),
                ('device', models.CharField(default='device', max_length=100)),
                ('truncated', models.BooleanField(default=False)),
                ('in_reply_to_status_id_str', models.CharField(default='in_reply_to_status_id_str', max_length=100)),
                ('in_reply_to_user_id_str', models.CharField(default='in_reply_to_user_id_str', max_length=100)),
                ('in_reply_to_screen_name', models.CharField(default='in_reply_to_screen_name', max_length=100)),
                ('retweet_count', models.IntegerField(default=0)),
                ('lang', models.CharField(default='language', max_length=100)),
                ('user_id_str', models.CharField(default='user_id_str', max_length=100)),
                ('name', models.CharField(default='name', max_length=100)),
                ('screen_name', models.CharField(default='screen_name', max_length=100)),
                ('location', models.CharField(default='location', max_length=100)),
                ('url', models.CharField(default='urls', max_length=100)),
                ('description', models.CharField(default='description', max_length=300)),
                ('verified', models.BooleanField(default=False)),
                ('followers_count', models.IntegerField(default=0)),
                ('friends_count', models.IntegerField(default=0)),
                ('listed_count', models.IntegerField(default=0)),
                ('favourites_count', models.IntegerField(default=0)),
                ('num_tweets', models.IntegerField(default=0)),
                ('user_created_at', models.DateTimeField()),
                ('utc_offset', models.CharField(default='utc_offset', max_length=100)),
                ('time_zone', models.DateTimeField()),
                ('geo_enabled', models.BooleanField(default=False)),
            ],
        ),
    ]
