# Generated by Django 2.1.7 on 2019-03-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='id',
        ),
        migrations.AlterField(
            model_name='tweet',
            name='tweet_id_str',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
