# Generated by Django 2.1.7 on 2019-03-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0002_remove_tweet_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='created_at',
            field=models.CharField(default='created_at', max_length=100, null=True),
        ),
    ]
