# Generated by Django 2.1.7 on 2019-03-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0004_auto_20190328_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='country',
            field=models.CharField(default='usa', max_length=200),
        ),
    ]
