# Generated by Django 2.1.7 on 2019-03-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0006_auto_20190328_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tweet_id_str',
            field=models.CharField(blank=True, default='tweet_id_str', max_length=100),
        ),
    ]
