# Generated by Django 2.1.7 on 2019-03-28 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0009_auto_20190328_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='geo_enabled',
        ),
    ]
