# Generated by Django 2.1.7 on 2019-03-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0010_remove_tweet_geo_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='geo_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
