# Generated by Django 2.1.7 on 2019-03-28 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0013_auto_20190328_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='created_at',
        ),
    ]
