# Generated by Django 2.1.7 on 2019-03-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0014_remove_tweet_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='created_at',
            field=models.CharField(blank=True, default='created_at', max_length=100),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='tweet_id_str',
            field=models.CharField(blank=True, default='tweet_id_str', max_length=100),
        ),
    ]
