# Generated by Django 2.1.7 on 2019-03-29 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0018_auto_20190328_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='country',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='device',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='favourites_count',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='followers_count',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='friends_count',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='geo_enabled',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='in_reply_to_screen_name',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='in_reply_to_status_id_str',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='in_reply_to_user_id_str',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='lang',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='listed_count',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='location',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='name',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='num_tweets',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='retweet_count',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='screen_name',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='text',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='time_zone',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='truncated',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='url',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='user_created_at',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='user_id_str',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='utc_offset',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='verified',
        ),
        migrations.AlterField(
            model_name='tweet',
            name='tweet_id_str',
            field=models.CharField(default='tweet_id_str', max_length=100, primary_key=True, serialize=False),
        ),
    ]
