# Generated by Django 2.1.7 on 2019-03-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0019_auto_20190329_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='created_at',
            field=models.CharField(default='created_at', max_length=100),
        ),
    ]
