# Generated by Django 2.1.7 on 2019-03-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0020_tweet_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='text',
            field=models.TextField(default='TextField', max_length=280),
        ),
    ]
