# Generated by Django 2.1.7 on 2019-03-29 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0021_tweet_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='device',
            field=models.CharField(default='device', max_length=100),
        ),
    ]
