# Generated by Django 2.1.7 on 2019-03-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0022_tweet_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='truncated',
            field=models.BooleanField(default=False),
        ),
    ]
