# Generated by Django 2.1.7 on 2019-03-31 14:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0023_tweet_truncated'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='country',
            field=models.CharField(default='usa', max_length=200),
        ),
        migrations.AddField(
            model_name='tweet',
            name='description',
            field=models.CharField(default='description', max_length=300),
        ),
        migrations.AddField(
            model_name='tweet',
            name='favourites_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tweet',
            name='followers_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tweet',
            name='friends_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tweet',
            name='geo_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tweet',
            name='in_reply_to_screen_name',
            field=models.CharField(default='in_reply_to_screen_name', max_length=100),
        ),
        migrations.AddField(
            model_name='tweet',
            name='in_reply_to_status_id_str',
            field=models.CharField(default='in_reply_to_status_id_str', max_length=100),
        ),
        migrations.AddField(
            model_name='tweet',
            name='in_reply_to_user_id_str',
            field=models.CharField(default='in_reply_to_user_id_str', max_length=100),
        ),
        migrations.AddField(
            model_name='tweet',
            name='lang',
            field=models.CharField(default='language', max_length=100),
        ),
        migrations.AddField(
            model_name='tweet',
            name='listed_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tweet',
            name='location',
            field=models.CharField(default='location', max_length=100),
        ),
        migrations.AddField(
            model_name='tweet',
            name='name',
            field=models.CharField(default='name', max_length=100),
        ),
        migrations.AddField(
            model_name='tweet',
            name='num_tweets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tweet',
            name='retweet_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tweet',
            name='screen_name',
            field=models.CharField(default='screen_name', max_length=100),
        ),
        migrations.AddField(
            model_name='tweet',
            name='time_zone',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 31, 14, 40, 19, 142768, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tweet',
            name='url',
            field=models.CharField(default='urls', max_length=100),
        ),
        migrations.AddField(
            model_name='tweet',
            name='user_id_str',
            field=models.CharField(default='user_id_str', max_length=100),
        ),
        migrations.AddField(
            model_name='tweet',
            name='utc_offset',
            field=models.CharField(default='utc_offset', max_length=100),
        ),
        migrations.AddField(
            model_name='tweet',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
