# Generated by Django 2.1.7 on 2019-03-31 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0024_auto_20190331_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='country',
        ),
    ]
