# Generated by Django 2.1.7 on 2019-03-31 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0026_tweet_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='country',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='favourites_count',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='followers_count',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='friends_count',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='geo_enabled',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='in_reply_to_screen_name',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='in_reply_to_status_id_str',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='in_reply_to_user_id_str',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='lang',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='listed_count',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='location',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='name',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='num_tweets',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='screen_name',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='time_zone',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='url',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='user_id_str',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='utc_offset',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='verified',
        ),
    ]
