# Generated by Django 2.1.7 on 2019-03-31 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0028_tweet_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='country',
        ),
    ]
