# Generated by Django 2.1.7 on 2019-03-31 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0029_remove_tweet_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='lang',
            field=models.CharField(default='language', max_length=100),
        ),
    ]
