# Generated by Django 2.1.7 on 2019-03-31 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0030_tweet_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='country',
            field=models.CharField(default='usa', max_length=200),
        ),
    ]
