# Generated by Django 2.1.7 on 2019-03-31 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0031_tweet_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='in_reply_to_screen_name',
            field=models.CharField(default='in_reply_to_screen_name', max_length=100),
        ),
        migrations.AddField(
            model_name='tweet',
            name='in_reply_to_status_id_str',
            field=models.CharField(default='in_reply_to_status_id_str', max_length=100),
        ),
        migrations.AddField(
            model_name='tweet',
            name='in_reply_to_user_id_str',
            field=models.CharField(default='in_reply_to_user_id_str', max_length=100),
        ),
    ]
