# Generated by Django 2.1.7 on 2019-03-31 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0032_auto_20190331_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='name',
            field=models.CharField(default='name', max_length=100),
        ),
        migrations.AddField(
            model_name='tweet',
            name='screen_name',
            field=models.CharField(default='screen_name', max_length=100),
        ),
        migrations.AddField(
            model_name='tweet',
            name='user_id_str',
            field=models.CharField(default='user_id_str', max_length=100),
        ),
    ]
