# Generated by Django 2.1.7 on 2019-03-31 18:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0033_auto_20190331_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='description',
            field=models.CharField(default='description', max_length=300),
        ),
        migrations.AddField(
            model_name='tweet',
            name='favourites_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tweet',
            name='followers_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tweet',
            name='friends_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tweet',
            name='geo_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tweet',
            name='listed_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tweet',
            name='num_tweets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tweet',
            name='time_zone',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 31, 18, 28, 41, 523543, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tweet',
            name='url',
            field=models.CharField(default='urls', max_length=100),
        ),
        migrations.AddField(
            model_name='tweet',
            name='user_created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 31, 18, 28, 49, 268799, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tweet',
            name='utc_offset',
            field=models.CharField(default='utc_offset', max_length=100),
        ),
        migrations.AddField(
            model_name='tweet',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
