# Generated by Django 2.1.7 on 2019-03-31 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0034_auto_20190331_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='in_reply_to_screen_name',
            field=models.CharField(default='in_reply_to_screen_name', max_length=100, null=True),
        ),
    ]
