# Generated by Django 2.1.7 on 2019-03-31 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0035_auto_20190331_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='in_reply_to_status_id_str',
            field=models.CharField(default='in_reply_to_status_id_str', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='in_reply_to_user_id_str',
            field=models.CharField(default='in_reply_to_user_id_str', max_length=100, null=True),
        ),
    ]
