# Generated by Django 2.1.7 on 2019-03-31 18:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0037_auto_20190331_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='time_zone',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 31, 18, 40, 36, 965257, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tweet',
            name='user_created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
