# Generated by Django 2.1.7 on 2019-03-31 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0038_auto_20190331_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='time_zone',
            field=models.DateTimeField(null=True),
        ),
    ]
