# Generated by Django 2.1.7 on 2019-04-01 20:14

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190323_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='oauth',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True),
        ),
    ]
