# Generated by Django 2.1.7 on 2019-04-01 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('query', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=60, verbose_name='user')),
                ('study_id', models.CharField(max_length=100, verbose_name='study_id')),
                ('tweets', models.ManyToManyField(to='query.Tweet')),
            ],
        ),
    ]
